template: |
  ## What's Changed
  $CHANGES

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR in $REPOSITORY'

categories:
  - title: '🚀 Features'
    labels: ['feat']
  - title: '🐛 Fixes'
    labels: ['fix']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor']
  - title: '📝 Docs'
    labels: ['docs']
  - title: '🧪 Tests'
    labels: ['tests']
  - title: '⬆️ Dependencies'
    labels: ['dependencies']
  - title: '🔒 Security'
    labels: ['security']

exclude-labels:
  - 'do-not-merge'
  - 'blocked'

version-resolver:
  major:
    labels: ['breaking']
  minor:
    labels: ['feat']
  patch:
    labels: ['fix', 'chore', 'docs', 'refactor', 'tests', 'dependencies', 'security']
  default: patch

autolabeler:
  - label: 'docs'
    files:
      - 'docs/**'