name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    name: Lint, type-check and tests (${{ matrix.os }} / py${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    env:
      QT_QPA_PLATFORM: offscreen

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install --upgrade pip
      - run: pip install wheel setuptools
      - run: pip install ruff mypy pytest
      - run: pip install -e .
      - run: ruff check .
      - run: mypy --ignore-missing-imports nova_prime
      - name: Run tests
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            xvfb-run -a pytest -q
          else
            pytest -q
          fi