---
name: Sync labels
"on":
  push:
    paths:
      - ".github/labels.yml"
      - ".github/workflows/sync-labels.yml"
  workflow_dispatch:

jobs:
  sync:
    permissions:
      contents: read
      issues: write
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          skip-delete: true
